# Generated by Django 5.0.7 on 2024-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pincode',
            name='code_type',
            field=models.CharField(choices=[('WASSCE', 'WASSCE'), ('BECE', 'BECE'), ('SHS PLACEMENT CODES', 'SHS PLACEMENT CODES')], max_length=100),
        ),
    ]
