# Generated by Django 5.0.7 on 2024-07-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_pincode_code_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
