# Generated by Django 5.0.7 on 2024-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_payment_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pincode',
            name='price',
            field=models.DecimalField(decimal_places=2, default=18, max_digits=10),
            preserve_default=False,
        ),
    ]
