# Generated by Django 5.0.7 on 2024-07-24 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_payment_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='code_type',
        ),
    ]
