# Generated by Django 5.0.7 on 2024-07-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_payment_code_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='timothysaatum@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
