# Generated by Django 5.0.7 on 2024-07-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
